version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:3002
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3002
    ports:
      - "3000:3000"
    depends_on:
      - express-api

  express-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
